apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: your-dockerhub-username/restaurant-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/fooddelivery"
            - name: JWT_SECRET
              value: "supersecretkey"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000/api/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP